# Generated by Django 5.0.2 on 2024-03-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("nascimento", models.DateTimeField(verbose_name="Data de nascimento")),
            ],
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_nome", models.CharField(max_length=200)),
                (
                    "funcionaro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teste.funcionario",
                    ),
                ),
            ],
        ),
    ]
