# Generated by Django 5.0.2 on 2024-03-10 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teste", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cargo",
            old_name="funcionaro",
            new_name="funcionario",
        ),
    ]
